# =====================================================
# FILE: user_experience_optimizer.py
# NAME: user_experience_optimizer.py
# PURPOSE: Adaptive UI engine for front-end agents.
# DETAILS: Reads feedback and session data to optimize prompts.
# VERSION: 1.0.1
# =====================================================

"""User Experience Optimizer – adaptive frontend intelligence."""

import sys
import threading
import time
from pathlib import Path

# Path injection
BLUEPRINT_ROOT = Path(__file__).parent.parent
if str(BLUEPRINT_ROOT) not in sys.path:
    sys.path.append(str(BLUEPRINT_ROOT))

try:
    from activation_demonstration.prompt_library_manager import (
        save_prompt,  # noqa: E402
    )
    from toolkits.dependency.core_utils import retry_on_exception  # noqa: E402
except ImportError:

    def save_prompt(agent, content):
        pass


from .feedback_aggregator import feedback_history  # noqa: E402


@retry_on_exception(max_retries=2)
def optimize_cycle():
    """Background optimization based on feedback loops."""
    if len(feedback_history) > 10:
        # Heuristic: If feedback scores drop, regenerate the discovery template
        save_prompt("Intake", "Optimized Discovery Template v2 - AutoGenerated")
        print("✨ UX Optimizer: Refined Intake prompt based on user feedback trends.")


def _run_loop():
    while True:
        try:
            optimize_cycle()
        except Exception:
            pass
        time.sleep(3600)  # Hourly optimization


# Start background thread
threading.Thread(target=_run_loop, daemon=True).start()
